feat: Adds structure for gRPC client metrics instrumentation
grpc-ecosystem/grpc-spring pull request #1021
Opened 2023-12-22 00:07 UTC by DNVindhya

This PR is one of the initial efforts to support gRFC [A66: OpenTelemetry Metrics](https://github.com/grpc/proposal/blob/master/A66-otel-stats.md) in gRPC-Spring. Even though the gRFC mentions OpenTelmetry, to keep it in sync with existing metrics, this PR as well as future ones will use Micrometer for instrumentation.

This PR adds the structure to collect gRPC metrics for [ClientInterceptor](https://grpc.github.io/grpc-java/javadoc/io/grpc/ClientInterceptor.html). To start with I have only added instrumentation for a single metric i.e `grpc.client.attempt.started`.

2023-12-26 19:40 UTC, fengli79 requested changes

2023-12-26 19:40 UTC, fengli79 commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInterceptor.java
> +        final MetricsClientStreamTracers.CallAttemptsTracerFactory tracerFactory =
Why create a tracer factory for each intercepted call? I'm under the impression that the factory can be reused to create a dedicated tracer for each call.

2023-12-26 19:40 UTC, fengli79 commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInterceptor.java
> +        return new SimpleForwardingClientCall<ReqT, RespT>(call) {
Please leave a TODO to clarify the purpose to wrap it with a SimpleForwardingClientCall here. I'm under the impression that this is for intercept the response/error events for other metrics in the future.

2023-12-26 19:40 UTC, fengli79 commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +        final CallAttemptsTracerFactory attemptsState;
Please make them private as well.

2023-12-26 19:40 UTC, fengli79 commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +            // Record here in case newClientStreamTracer() would never be called.
Why newClientStreamTracer would never be called? Shall it be always invoked?

2023-12-26 19:40 UTC, fengli79 commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +            if (attemptsPerCall.get() > 0) {
Why we need this atomic? Why not increment the attempt counter when a new stream tracer get created?

2023-12-26 19:40 UTC, fengli79 commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsMeters.java
> +public class MetricsMeters {
Can we remove this abstraction on top of MeterProvider<Counter>? Seems overweighted.

2023-12-27 18:54 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInterceptor.java
> +    private final MeterRegistry registry;
AFAICT the registry is only used inside the constructor, so there is no need to store it in a variable.

2023-12-27 18:54 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInstruments.java
> +        MetricsMeters.Builder builder = MetricsMeters.newBuilder();
IMO you could just inline this:

````java
return MetricsMeters.newBuilder()
    ...
    .build();
````

2023-12-27 18:54 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +                    .withTags((Tags.of("grpc.method", fullMethodName)))
AFAICT here are redundant parenthesis.

2023-12-27 18:55 UTC, ST-DDT commented
What is the difference between this and https://github.com/grpc-ecosystem/grpc-spring/pull/1010?

2024-01-04 01:58 UTC, DNVindhya reviewed
Addressed comments. PTAL

> What is the difference between this and #1010?
Accidentally rebased in the branch, and that pulled all other merged changes from master as well. So left it as draft (to be removed once this PR is reviewed) and started this PR.

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInstruments.java
> +        MetricsMeters.Builder builder = MetricsMeters.newBuilder();
The builder will be used to add future metrics counters and timers. So leaving it as if for now.

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInterceptor.java
> +        final MetricsClientStreamTracers.CallAttemptsTracerFactory tracerFactory =
Along with creating tracer factory per call, we also record rpc attempt started metric. So it cannot be reused across calls.

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInterceptor.java
> +        return new SimpleForwardingClientCall<ReqT, RespT>(call) {
Added TODO. You are right, it will be used to intercept metrics instrumentation on call completion event.

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsMeters.java
> +public class MetricsMeters {
Added this abstraction to facilitate two things:
1. Provides ability to set individual meters which helps in selectively enabling or disabling specific metrics.
2. Acts as a data class to hold all metric metrics.
Let me know if you still think this seems redundant.

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInstruments.java
> +    static final String CLIENT_ATTEMPT_STARTED = "grpc.client.attempt.started";
Made it package private so that it can accessible for tests as well. I think we can define it again in tests.
Updated access modifier and added comment.

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInstruments.java
> +    static MetricsMeters micrometerInstruments(MeterRegistry registry) {
Done

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInstruments.java
> +                .description("The total number of RPC attempts started, including those that have not completed.")
The description is from A66 [metric description](https://github.com/grpc/proposal/blob/master/A66-otel-stats.md#client-per-attempt-instruments). Updated.

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInterceptor.java
> + * A gRPC client interceptor that will collect gRPC metrics.
Done

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInterceptor.java
> +     * Creates a new gRPC client interceptor that will collect metrics into the given
Done

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInterceptor.java
> +    public MetricsClientInterceptor(MeterRegistry meterRegistry) {
Done

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInterceptor.java
> +     * @param meterRegistry The meter registry to use.
Done

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +        final CallAttemptsTracerFactory attemptsState;
Updated

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +            // Record here in case newClientStreamTracer() would never be called.
IIUC stream creation does not happen as soon as the call starts. If the call gets cancelled, even before stream is created `newClientStreamTracer()` will not be called.

2024-01-04 01:58 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +            if (attemptsPerCall.get() > 0) {
As soon the client call is created, it counts as an attempt. So as answered in the other [comment](https://github.com/grpc-ecosystem/grpc-spring/pull/1021/files#r1436584316) there is no certainty that `newClientStreamTracer()` will be called without fail.

2024-01-04 02:56 UTC, fengli79 submitted a review, later dismissed

2024-01-04 03:02 UTC, fengli79 commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInterceptor.java
> +        final MetricsClientStreamTracers.CallAttemptsTracerFactory tracerFactory =
SG, worth to clarify that this is a per call stream tracer factory, which creates stream tracers for each attempt under the same call, each call needs a dedicated factory, as they share the same method descriptor.

2024-01-04 03:02 UTC, fengli79 commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsMeters.java
> +public class MetricsMeters {
LGTM

2024-01-04 18:17 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInstruments.java
> +    static MetricsMeters instruments(MeterRegistry registry) {
I would probably go for `newMeters` or `newMetricsMeters` as `instruments` doesn't explain well what this method does.

2024-01-04 18:21 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInterceptor.java
> +        return new SimpleForwardingClientCall<ReqT, RespT>(call) {
IMO the TODO comment is not very clear to me.

> // TODO(dnvindhya): Add purpose of wrapping with SimpleForwardingClientCall

Maybe change it to:

> // TODO(dnvindhya): Collect the actual response/error in the SimpleForwardingClientCall

2024-01-04 18:48 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInstruments.java
> +    static MetricsMeters instruments(MeterRegistry registry) {
Make sense. How about `newClientMetricsMeters`?

2024-01-04 18:53 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInstruments.java
> +    static MetricsMeters instruments(MeterRegistry registry) {
Sounds good.

2024-01-04 19:33 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInterceptor.java
> +        final MetricsClientStreamTracers.CallAttemptsTracerFactory tracerFactory =
Added comment to clarify the explicit usage of factory in every call.

2024-01-04 19:33 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInterceptor.java
> +        return new SimpleForwardingClientCall<ReqT, RespT>(call) {
Updated

2024-01-04 19:33 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInstruments.java
> +    static MetricsMeters instruments(MeterRegistry registry) {
Updated

2024-01-05 14:51 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +            if (attemptsPerCall.get() > 0) {
IMO would be more clear, if this would use a boolean instead.

````java
// The first call is already counted in the constructor
if (first) {
    this.metricsMeters.getAttemptCounter()
                        .withTags(Tags.of("grpc.method", fullMethodName))
                        .increment();
} else {
  first = false;
}
````

Since this method ends afterwards, the value doesn't have to be atomic AFAICT.

2024-01-05 14:52 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +            }
IMO this should either wrap around the actual increment or not be relevant at all.

2024-01-05 14:53 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +                final MetricsMeters metricsMeters) {
```suggestion
        CallAttemptsTracerFactory(String fullMethodName, MetricsMeters metricsMeters) {
```

2024-01-05 14:55 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInstruments.java
> +public class MetricsClientInstruments {
Please make these container classes final with a private constructor.

2024-01-05 14:55 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +public class MetricsClientStreamTracers {
Same here

2024-01-08 21:59 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +            }
Removed it as this is not needed for `grpc.client.attempt.started` metric.

2024-01-08 21:59 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +            if (attemptsPerCall.get() > 0) {
Updated to use boolean for now. PTAL

2024-01-08 21:59 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +                final MetricsMeters metricsMeters) {
Done

2024-01-08 21:59 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientInstruments.java
> +public class MetricsClientInstruments {
Updated

2024-01-08 21:59 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +public class MetricsClientStreamTracers {
Updated

2024-01-09 11:28 UTC, ST-DDT approved these changes
Implementation wise this looks good to me.

This is missing for the inclusion in an actual release:

- the metric auto configuration
- and some tests

My concerns with this PR:

- This is only a partial implementation of the entire metrics feature
- This should be implemented in the micrometer grpc instrumentation repo (where there are already two different implementations of it)

2024-01-09 19:08 UTC, DNVindhya commented
Thanks for all your detailed comments. This PR was added with the intention to get the basic structure in place to add a single client metric, other metrics and unit tests will be added in subsequent PRs. Plan is to enable metric auto configuration, once all the metrics are in.

> * This should be implemented in the micrometer grpc instrumentation repo (where there are already two different implementations of it)

Since I am breaking down the metrics features (for ease of review and faster iteration) into multiple PRs, I am planning to move these to Micrometer GRPC instrumentation repo after the feature is completely checked in and ready to be enabled. 

I hope I addressed your concerns. Please let me know if there are any blockers to merge the PR.

2024-01-09 22:28 UTC, ST-DDT commented
> Please let me know if there are any blockers to merge the PR.

All good. LGTM.

2024-01-09 23:52 UTC, merged