feat: apply grpc service config from consul (#1045)
grpc-ecosystem/grpc-spring pull request #1046
Opened 2024-02-02 09:04 UTC by onyn

Closes #1045

2024-02-03 11:43 UTC, ST-DDT requested changes
Could you please replace `var` with actual types?

2024-02-03 21:36 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolverTest.java
> +        assertThat(serviceConf.getConfig()).isNotNull();
Please check at least one value from the config.

2024-02-03 21:36 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/client/nameresolver/TestableListener.java
> +    private boolean errorWasSet = false;
```suggestion
    private NameResolver.ResolutionResult result;
    private Status error;
    private boolean resultWasSet = false;
    private boolean errorWasSet = false;
```

2024-02-03 21:36 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
> +            }
Could you please move this block to a separate method?
Maybe let it return `ConfigOrError`. I wished there was a method for that in the grpc api/core library.

Also the DNSNameresolver does a lot more with the configs, not sure which parts we should copy from that:
https://github.com/grpc/grpc-java/blob/3202370684ec74a8e986a116b3e1476ff0a3fedc/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L489

2024-02-04 07:08 UTC, onyn commented on grpc-client-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolverTest.java
> +        assertThat(serviceConf.getConfig()).isNotNull();
I tried. But `getConfig()` returns object of type `Object`. Real type of this object is `io.grpc.internal.ManagedChannelServiceConfig` which have package level visibility. Value test can be done only by using reflection or creating proxy class in `io.grpc.internal` package which opens `ManagedChannelServiceConfig` for test. But this makes test fragile. I can do it if you ok with this.

2024-02-04 07:22 UTC, onyn commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
> +            }
Ok, will move it.

DnsNameResolver uses array of service configs with rules to which service which config should be applied ([more on this](https://github.com/grpc/proposal/blob/master/A2-service-configs-in-dns.md#canarying-changes)). I choose not to bring in this complication. But if you want, I can implement this exactly like in DnsNameResolver.

2024-02-04 08:13 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolverTest.java
> +        assertThat(serviceConf.getConfig()).isNotNull();
If it is that deeply hidden, then we dont need additional test for it.

2024-02-04 08:35 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
> +            }
It looks like they already put quite some though into it. I would like to get feedback from the other grpc developers on this.
@DNVindhya Do you have a contact that could enlighten us or help us getting an API method for String->ServiceConfig?

2024-02-05 18:49 UTC, DNVindhya commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
> +            }
Opening a grpc-java issue for this will be apt.

2024-03-13 08:31 UTC, ST-DDT commented
Please resolve the merge conflicts.

2024-03-13 08:34 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
> +            }
@onyn any updates one this? Do you have a link for the api request?

2024-03-13 10:19 UTC, onyn commented
Done. Two questions remains:

1. Should we support [canarying changes](https://github.com/grpc/proposal/blob/master/A2-service-configs-in-dns.md#canarying-changes) feature of DNS resolver? This may be supported in the future, using separate metadata key in case of demand.
2. Currently GRPC doesn't expose methods for parsing json string into `ConfigOrError` object. Shoud we wait for it?

2024-03-13 12:02 UTC, ST-DDT commented
Thanks for your fast response.

Lets wait a bit on how upstream decides on the API topic.

2024-03-25 09:44 UTC, onyn commented
[That](https://github.com/grpc/grpc-java/issues/11008#issuecomment-2010949346) was expected.

So, just one question left:

1. Should we support [canarying changes](https://github.com/grpc/proposal/blob/master/A2-service-configs-in-dns.md#canarying-changes) feature of DNS resolver? This may be supported in the future, using separate metadata key in case of demand.
2. ~~Currently GRPC doesn't expose methods for parsing json string into `ConfigOrError` object. Shoud we wait for it?~~

2024-03-25 18:16 UTC, ST-DDT commented
> 1. Should we support [canarying changes](https://github.com/grpc/proposal/blob/master/A2-service-configs-in-dns.md?rgh-link-date=2024-03-25T09%3A44%3A59Z#canarying-changes) feature of DNS resolver?

No, just keep it simple. If grpc adds an official API, we can adopt it then.

2024-03-26 09:44 UTC, onyn commented
Rebased and squashed.

2024-03-26 11:23 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
> +            this.savedListener.onResult(result.build());
IMO you can directly build the result in line 372 instead of delaying it till here. There aren't any intermediate calls to the builder so we can improve the readability by building early.

2024-03-26 11:23 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
> +        for (final ServiceInstance inst : instances) {
Should we shuffle them to add some randomness to this?

2024-03-26 13:17 UTC, onyn commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
> +        for (final ServiceInstance inst : instances) {
Better to refuse any config if there's differences in any single service from others. And log it with "warn" level to make the problem visible. There's no sense to prefer one config over another, because all service instances are equivalent from grpc's point of view. We should force service operators to configure their instances with same service config.

2024-03-27 00:04 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
> +        for (final ServiceInstance inst : instances) {
The thing is that when the config changes, it will only slowly propagate to all new instances.
It would then cause these warnings.
Not sure about selecting a random one though. Maybe a sticky random (keep the config while it is provided by at least one instance).

2024-03-27 10:49 UTC, onyn commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
> +        for (final ServiceInstance inst : instances) {
That makes sense. Anyway, I see no benefits in randomness (including sticky one). We can't do anything in case of human error while configuring service config. And predictable approach works better in case of rolling update.

2024-03-29 21:16 UTC, ST-DDT approved these changes
Looks good to me.

2024-03-29 21:16 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
> +                    .setServiceConfig(resolveServiceConfig(newInstanceList)).build());
```suggestion
                    .setServiceConfig(resolveServiceConfig(newInstanceList))
                    .build());
```

2024-04-02 07:34 UTC, onyn commented
Rebased & squashed.

2024-04-04 22:03 UTC, ST-DDT approved these changes

2024-04-12 06:57 UTC, yidongnan approved these changes

2024-04-12 06:58 UTC, merged