Add instrumentation tags to grpc metrics
grpc-ecosystem/grpc-spring pull request #1081
Opened 2024-03-27 22:32 UTC by stanley-cheung

Add two tags to the A66 metrics exported by the MetricsStreamTracers

instrumentation_source: grpc-spring
instrumentation_version: <current project version>

2024-03-27 22:53 UTC, fengli79 approved these changes

2024-03-27 22:55 UTC, fengli79 requested changes

2024-03-27 22:55 UTC, fengli79 commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/Versions.java
> +    public static final String PROJECT_VERSION = "v3.0.0.RELEASE";
We should not hardcode this. It needs come from the build process.

2024-03-27 23:10 UTC, stanley-cheung commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/Versions.java
> +    public static final String PROJECT_VERSION = "v3.0.0.RELEASE";
Fixed

2024-03-28 00:00 UTC, stanley-cheung commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/Versions.java
> +    public static final String PROJECT_VERSION = "v3.0.0.RELEASE";
I end up taking a slightly different approach. Instead of doing a string replace, which will _modify the source file_, which seems undesirable, I now _generate_ the `Versions.java` file as part of the `build.gradle` build step. This seems cleaner, because that generated file can later be cleaned up by `./gradlew clean`.

2024-03-28 04:35 UTC, stanley-cheung commented
I can't quite figure out how to fix the current gradle build error.

```
$ ./gradlew publishToMavenLocal


> Task :grpc-common-spring-boot:sourcesJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':grpc-common-spring-boot:sourcesJar' (type 'Jar').
  - Gradle detected a problem with the following location: '/usr/local/google/home/stanleycheung/grpc-spring/grpc-common-spring-boot/src/main/java'.
    
    Reason: Task ':grpc-common-spring-boot:sourcesJar' uses this output of task ':createVersionsFile' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':createVersionsFile' as an input of ':grpc-common-spring-boot:sourcesJar'.
      2. Declare an explicit dependency on ':createVersionsFile' from ':grpc-common-spring-boot:sourcesJar' using Task#dependsOn.
      3. Declare an explicit dependency on ':createVersionsFile' from ':grpc-common-spring-boot:sourcesJar' using Task#mustRunAfter.
```

2024-03-28 20:30 UTC, stanley-cheung commented
Some more work to be done...

2024-03-28 22:11 UTC, fengli79 commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +                            "instrumentation_source", Constants.INSTRUMENTATION_SOURCE_TAG_VALUE,
Also, the label keys can be encapsulated in this file instead of define in the Constants.java.

2024-03-28 22:17 UTC, fengli79 commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/Constants.java.template
> +    public static final String INSTRUMENTATION_SOURCE_TAG_VALUE = "grpc-spring";
s/INSTRUMENTATION_SOURCE_TAG_VALUE/LIBRARY_NAME

2024-03-28 23:29 UTC, ST-DDT commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/Constants.java.template
> +    public static final String PROJECT_VERSION = "@versionStringPlaceholder@";
Instead of project build tools you could also use `Constants.class.getPackage().getImplementationVersion()` (if the related properties for the jar goal are configured)

2024-03-29 17:59 UTC, stanley-cheung commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +                            "instrumentation_source", Constants.INSTRUMENTATION_SOURCE_TAG_VALUE,
Fixed.

2024-03-29 17:59 UTC, stanley-cheung commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +                            "instrumentation_version", Constants.PROJECT_VERSION);
Fixed

2024-03-29 18:00 UTC, stanley-cheung commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/metrics/MetricsClientStreamTracers.java
> +                            "instrumentation_source", Constants.INSTRUMENTATION_SOURCE_TAG_VALUE,
Done.

2024-03-29 18:00 UTC, stanley-cheung commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/Constants.java.template
> +    public static final String PROJECT_VERSION = "@versionStringPlaceholder@";
Fixed

2024-03-29 18:00 UTC, stanley-cheung commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/Constants.java.template
> +    public static final String INSTRUMENTATION_SOURCE_TAG_VALUE = "grpc-spring";
Fixed

2024-03-29 18:00 UTC, stanley-cheung commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/Constants.java.template
> +    public static final String PROJECT_VERSION = "@versionStringPlaceholder@";
Will look into that, probably in a subsequent PR. Thanks for the suggestions.

2024-03-29 18:10 UTC, stanley-cheung commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/Constants.java.template
> +    public static final String PROJECT_VERSION = "@versionStringPlaceholder@";
Actually that works. I removed the build generation step. Thanks for the suggestion again!

2024-03-29 21:12 UTC, ST-DDT commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/Constants.java
> +
```suggestion

```

2024-03-29 21:12 UTC, ST-DDT commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/Constants.java
> +
```suggestion

```

2024-03-29 21:12 UTC, ST-DDT commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/Constants.java
> + * Class that contains shared constants
```suggestion
 * Class that contains shared constants.
```

2024-03-29 21:18 UTC, stanley-cheung commented
> > Add two tags to the A66 metrics exported by the MetricsStreamTracers
> 
> I haven't found a reason why these tags should be included. Is it part of the spec?

Yes this is part of an internal spec that will help us distinguish where the metrics originate.

2024-03-29 21:21 UTC, ST-DDT approved these changes
I'm not sure whether the tags should be included for everyone.
But implementation wise this looks good to me.
(Spring has a bean for adding tags to metrics).

2024-04-01 21:32 UTC, DNVindhya approved these changes
LGTM

2024-04-01 22:35 UTC, fengli79 approved these changes

2024-04-01 22:50 UTC, merged