Feat(deadline) add deadline property for client
grpc-ecosystem/grpc-spring pull request #1132
Opened 2024-08-03 12:34 UTC by batsura-sa

Hi! Could we add deadline property for client?

2024-09-02 19:39 UTC, ST-DDT requested changes

2024-09-02 19:39 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/deadline/DeadlineHelper.java
> +    public static StubTransformer deadlineStubTransformer(final GrpcChannelsProperties props) {
Maybe just inline this method?

2024-09-02 19:39 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelProperties.java
> +     * @see #setDeadline(Duration)
This should probably refer to the channel builder method this refers to. (Instead of linking to itself)

2024-09-02 19:39 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelProperties.java
> +    // --------------------------------------------------
Please put the deadline block after the address property (as the address is kind of more important).

2024-09-02 19:39 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelProperties.java
> +     * Set the deadline for the stub. If nothing is configured then the deadline will not be used by default
```suggestion
     * Set the deadline for the stub. If nothing is configured then the deadline will not be used by default.
```

Maybe mention what happens if zero is set.

2024-09-02 19:39 UTC, ST-DDT commented on tests/src/test/java/net/devh/boot/grpc/test/setup/DeadlineTests.java
> +    }
Please add a test that works at first, but then runs into the timeout.
Maybe using the echo call (if it exists).

2024-09-02 19:39 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/deadline/DeadlineHelper.java
> +                return stub.withDeadline(Deadline.after(channelProps.getDeadline().toMillis(), TimeUnit.MILLISECONDS));
Isn't the deadline a global limit instead of a per call limit? Is that intentional?

https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html#withDeadline(io.grpc.Deadline)

2024-09-03 09:08 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/deadline/DeadlineHelper.java
> +    public static StubTransformer deadlineStubTransformer(final GrpcChannelsProperties props) {
\+

2024-09-03 09:11 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelProperties.java
> +    // --------------------------------------------------
\+

2024-09-03 09:19 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/deadline/DeadlineHelper.java
> +                return stub.withDeadline(Deadline.after(channelProps.getDeadline().toMillis(), TimeUnit.MILLISECONDS));
Thanks for noticing. Fixed when creating stub on stub.withDeadlineAfter(channelProps.getDeadline().toMillis(), TimeUnit.MILLISECONDS);

2024-09-03 10:04 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/deadline/DeadlineHelper.java
> +                return stub.withDeadline(Deadline.after(channelProps.getDeadline().toMillis(), TimeUnit.MILLISECONDS));
That method has the same limitation.

2024-09-03 12:42 UTC, batsura-sa commented on tests/src/test/java/net/devh/boot/grpc/test/setup/DeadlineTests.java
> +    }
\+

2024-09-03 12:47 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelProperties.java
> +     * @see #setDeadline(Duration)
Is this necessary? Unfortunately I don't know how to do this. I need a hint.

2024-09-03 13:23 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/deadline/DeadlineHelper.java
> +                return stub.withDeadline(Deadline.after(channelProps.getDeadline().toMillis(), TimeUnit.MILLISECONDS));
It's OK. Many services setup deadlineAfter from application.yaml. Maybe the single place for deadline properties is not bad?

2024-09-03 23:03 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientDeadlineAutoConfiguration.java
> +     * Creates a {@link StubTransformer} bean that will add the call credentials to the created stubs.
This sentence looks like a copy-paste from a security interceptor. The javadoc has to be updated.

2024-09-03 23:03 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientDeadlineAutoConfiguration.java
> +     * @see AbstractStub#withDeadline(io.grpc.Deadline)
This refers to the wrong method.

2024-09-04 05:16 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/interceptor/DeadlineSetupClientInterceptor.java
> +            return next.newCall(method, callOptions.withDeadlineAfter(duration.toMillis(), TimeUnit.MILLISECONDS));
Good question. Maybe it's worth leaving the simple implementation when the deadline from the configuration is more important

2024-09-04 06:15 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelProperties.java
> +     * @see #setDeadline(Duration)
\+

2024-09-04 06:16 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientDeadlineAutoConfiguration.java
> +     * Creates a {@link StubTransformer} bean that will add the call credentials to the created stubs.
\+

2024-09-04 06:25 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientDeadlineAutoConfiguration.java
> +     * @see AbstractStub#withDeadline(io.grpc.Deadline)
\+

2024-09-04 12:01 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/interceptor/DeadlineSetupClientInterceptor.java
> +            return next.newCall(method, callOptions.withDeadlineAfter(duration.toMillis(), TimeUnit.MILLISECONDS));
I think an explicit deadline should win over a central hardcoded one.
(It is more likely that you want to configure a deadline that is longer for one (streaming) call than the config states, then the other way round)

2024-09-04 12:38 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/interceptor/DeadlineSetupClientInterceptor.java
> +    private final CallOptions.Key<Duration> deadlineDuration;
\+

2024-09-04 14:25 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientDeadlineAutoConfiguration.java
> +    StubTransformer deadlineStubTransformer(final GrpcChannelsProperties props) {
Did it in StubTransformer deadlineStubTransformer(final GrpcChannelsProperties props), don't now how to did it in  @Bean
    GrpcChannelConfigurer deadlineGrpcChannelConfigurer(final GrpcChannelsProperties props) {
}

2024-09-04 18:59 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/interceptor/DeadlineSetupClientInterceptor.java
> +@GrpcGlobalClientInterceptor
This annotation is no longer needed.

```suggestion
```

2024-09-04 18:59 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/interceptor/DeadlineSetupClientInterceptor.java
> +        if (defaultDeadline != null) {
```suggestion
        if (defaultDeadline != null && callOptions.getDeadline() == null) {
```

2024-09-04 19:00 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientDeadlineAutoConfiguration.java
> +    StubTransformer deadlineStubTransformer(final GrpcChannelsProperties props) {
It should be as simple as replacing the interface you are trying to implement with the new one.
If that posses any issues, please paste the error here please.

2024-09-05 05:49 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientDeadlineAutoConfiguration.java
> +    StubTransformer deadlineStubTransformer(final GrpcChannelsProperties props) {
Found the channel.intercept method. It's really simple.

2024-09-05 08:58 UTC, ST-DDT reviewed
Looks good to me. Only a few small changes, and then this is good to go.

2024-09-05 08:58 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientDeadlineAutoConfiguration.java
> +     * @see DeadlineSetupClientInterceptor#interceptCall(MethodDescriptor, CallOptions, Channel)
IMO we can simplify this to just the classname, because there is only one method in there.

```suggestion
     * @see DeadlineSetupClientInterceptor
```

2024-09-05 08:58 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientDeadlineAutoConfiguration.java
> +     * props.
```suggestion
     * Creates a {@link GrpcChannelConfigurer} bean applying the default deadline from config to each new call using a {@link ClientInterceptor}.
```

2024-09-05 08:58 UTC, ST-DDT commented on tests/src/test/java/net/devh/boot/grpc/test/setup/DeadlineTests.java
> +public class DeadlineTests {
Please add a test showing that the manually configured deadline takes precedence of the config one.

2024-09-05 08:58 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +			"description": "A deadline is used to specify a point in time past which a client is unwilling to wait for a response from a server"
This needs to be updated.

2024-09-05 08:58 UTC, ST-DDT commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelProperties.java
> +     * will not be used by default. If zero value is configured, the deadline will not be used.
```suggestion
     * Set the default deadline duration for new calls (on a per call basis).
     * By default and if zero value is configured, the deadline will not be used.
     * The default deadline will be ignored, if a deadline has been applied manually.
```

2024-09-05 09:19 UTC, genuss commented
What do you think about calling the configured property _timeout_ instead of _deadline_? I believe the current name create some confusion. Deadline in context of GRPC has special meaning and that is "An absolute point in time", although the configured property is a duration.

2024-09-05 10:48 UTC, batsura-sa commented
> What do you think about calling the configured property _timeout_ instead of _deadline_? I believe the current name create some confusion. Deadline in context of GRPC has special meaning and that is "An absolute point in time", although the configured property is a duration.

Will there be confusion because we set timeout in the configuration, but in fact we set deadline?

2024-09-05 10:55 UTC, genuss commented
> Will there be confusion because we set timeout in the configuration, but in fact we set deadline?

I don't think so as you don't set it as-is, but convert it to another object by calling `withDeadlineAfter`

2024-09-05 11:20 UTC, batsura-sa commented on tests/src/test/java/net/devh/boot/grpc/test/setup/DeadlineTests.java
> +public class DeadlineTests {
\+

2024-09-05 12:15 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +			"description": "A deadline is used to specify a point in time past which a client is unwilling to wait for a response from a server"
\+

2024-09-05 12:18 UTC, batsura-sa commented
> > Will there be confusion because we set timeout in the configuration, but in fact we set deadline?
> 
> I don't think so as you don't set it as-is, but convert it to another object by calling `withDeadlineAfter`

OK. For example grpc.client.GLOBAL.timeout=1s ? right?

2024-09-06 05:25 UTC, genuss commented
>OK. For example grpc.client.GLOBAL.timeout=1s ? right?

Exactly!

2024-09-06 07:03 UTC, batsura-sa commented
> > OK. For example grpc.client.GLOBAL.timeout=1s ? right?
> 
> Exactly 👍

Done, not sure about the names. We can improve the source code or comments if you think it is necessary.

2024-09-06 09:46 UTC, batsura-sa commented on grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/interceptor/TimeoutSetupClientInterceptor.java
> +        if (timeout != null && callOptions.getDeadline() == null) {
\+

2024-09-06 09:47 UTC, batsura-sa commented on tests/src/test/java/net/devh/boot/grpc/test/setup/TimeoutSetupTests.java
> +        }
Pardon. Done.

2024-09-06 10:14 UTC, batsura-sa commented
May be rename the timeout property to requestTimeout? Like this "grpc.client.GLOBAL.requestTimeout=1s",

2024-09-06 10:33 UTC, ST-DDT commented
> May be rename the timeout property to requestTimeout? Like this "grpc.client.GLOBAL.requestTimeout=1s". IMHO timeout is really abstract property name.

requestTimeout or defaultRequestTimeout?

2024-09-06 10:39 UTC, batsura-sa commented
> > May be rename the timeout property to requestTimeout? Like this "grpc.client.GLOBAL.requestTimeout=1s". IMHO timeout is really abstract property name.
> 
> requestTimeout or defaultRequestTimeout?

I like both, can you choose one?

2024-09-06 11:04 UTC, ST-DDT commented
> I like both, can you choose one? May be defaultRequestTimeout is better.

Then `defaultRequestTimeout` it is.

2024-09-06 16:42 UTC, batsura-sa commented
> > I like both, can you choose one? May be defaultRequestTimeout is better.
> 
> Then `defaultRequestTimeout` it is.

Done. Let me know, please if we can do comments or code better.

2024-09-06 19:08 UTC, ST-DDT approved these changes

2024-09-07 06:46 UTC, ST-DDT approved these changes
Looks good to me.
Thanks for your contribution. ❤️

2024-09-07 08:24 UTC, batsura-sa commented
> Looks good to me. Thanks for your contribution. ❤️

Thanks for the review, it was very helpful. Is it possible to see this feature in the release? What needs to be done for this?

2024-09-07 12:18 UTC, ST-DDT commented
The maintainers have to review/merge it.

2024-10-27 14:51 UTC, yidongnan approved these changes
LGTM

2024-10-27 14:52 UTC, merged