feat: Allow annotation GrpcClient for target type 'annotation'
grpc-ecosystem/grpc-spring pull request #993
Opened 2023-11-18 12:19 UTC by 313hemant313

Allow annotation GrpcClient for target type 'annotation'. #991

2023-11-18 13:11 UTC, ST-DDT requested changes
Please add a test case for this.

2023-11-18 13:56 UTC, 313hemant313 commented
@ST-DDT Test case added, please review.

2023-11-18 14:14 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/metaannotation/GrpcClientWrapper.java
> +public @interface GrpcClientWrapper {
AFAICT this is only for the test isn't it? Please move it to the tests.

2023-11-18 14:35 UTC, 313hemant313 commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/metaannotation/GrpcClientWrapper.java
> +public @interface GrpcClientWrapper {
Correct, my bad. Moved to test.

2023-11-18 15:34 UTC, ST-DDT commented
CI is red.

2023-11-18 16:52 UTC, 313hemant313 commented
Updated after ./gradlew :tests:spotlessApply. please run the job.

2023-11-18 21:08 UTC, ST-DDT commented
Please pull and run the `./gradlew spotlessApply` command again.

2023-11-19 03:25 UTC, 313hemant313 commented
./gradlew check and  spotlessApply are success now.

2023-11-19 09:11 UTC, 313hemant313 commented
I was using java 19 version. changed it to 17 and pushed a new change with ./gradlew :tests:spotlessApply

2023-11-19 09:41 UTC, ST-DDT approved these changes
Looks good to me. Thanks for your contribution. ❤️ 

FFR: I find PRs easier to review if they aren't force pushed in between.

2023-11-19 10:33 UTC, 313hemant313 commented
> FFR: I find PRs easier to review if they aren't force pushed in between.
Okay.

2023-11-19 11:29 UTC, ST-DDT commented
> How to get this merged ?

You cannot merge this. We will have another reviewer look at this and then merge it ourselves.

2023-11-20 10:16 UTC, yidongnan approved these changes
LGTM, Thanks for your contribution.

2023-11-20 10:17 UTC, merged